trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  ArtifactName: TOTVS-Carol-Analytics
  FeedName: totvs-carol-analytics
  FeedDescription: 'CarolApp do GoodData Cloud'

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'
    versionFilePath: '$(build.sourcesDirectory)/.nvmrc'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install and build'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build-angular'
    workingDir: '$(build.sourcesDirectory)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.sourcesDirectory)/dist/$(ArtifactName)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)-$(ArtifactVersion).zip'
    replaceExistingArchive: true
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/$(ArtifactName)-$(ArtifactVersion).zip'
    artifact: '$(ArtifactName)-$(ArtifactVersion).zip'
    publishLocation: 'pipeline'
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '4814bdf4-e908-4a6c-951f-33996fa5e5db/fbab36c1-750b-4a46-8e1a-26c68726e78a'
    vstsFeedPackagePublish: '$(FeedName)'
    versionOption: '$(ArtifactVersion)'
    versionPublish: '$(ArtifactVersionNumber)'
    packagePublishDescription: '$(FeedDescription)'
    verbosity: 'Debug'